# Generated by Django 6.0.3 on 2026-05-18 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_indicacaolivros'),
        ('biblioteca', '0006_usuario_is_professor'),
    ]

    operations = [
    ]
