# Generated by Django 6.0.3 on 2026-05-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_merge_0006_indicacaolivros_0006_usuario_is_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicacaolivros',
            name='isbn',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
    ]
